name: SVUHC
version: 1.0
main: fr.azrotho.svuhc.SVUhc
author: Azrotho
api-version: 1.20
commands:
  team:
    description: "Admin Command: Manage teams"
    usage: "/team <args>"
  nick:
    description: "Admin Command: Manage nicknames"
    usage: "/nick <args>"