name: SVUHC
version: 1.0
main: fr.azrotho.svuhc.SVUhc
author: Azrotho
api-version: 1.20
commands:
  team:
    description: "Admin Command: Manage teams"
    usage: "/team <setTeam/getPlayerTeams> [Player] [garcon/fille]"
  start:
    description: "Admin Command: Start the game"
    usage: "/start"
  couple:
    description: "Demander à un joueur de se mettre en couple avec vous"
    usage: "/couple <Player>"
    aliases: [pecho, declaration]
  bisou:
    description: "Embrasser un joueur"
    usage: "/bisou"
    aliases: [kiss, kissme]
  uwu:
    description: "UwU"
    usage: "/uwu"
    aliases: [owo]
  colleserre:
    description: "Colle un joueur"
    usage: "/colleserre"