name: SVUHC
version: 1.0
main: fr.azrotho.svuhc.SVUhc
author: Azrotho
api-version: 1.20
commands:
  team:
    description: "Admin Command: Manage teams"
    usage: "/team <args>"
  start:
    description: "Admin Command: Start the game"
    usage: "/start"
  couple:
    description: "Demander à un joueur de se mettre en couple avec vous"
    usage: "/couple <args>"
    aliases: [pecho, declaration]